// Tabler Icons (MIT License) - https://tabler.io/icons
// Vendored assets are stored in `src/ui/icons/tabler/`.

export global AppIcons {
    out property <image> plus: @image-url("icons/tabler/plus.svg");
    out property <image> search: @image-url("icons/tabler/search.svg");
    out property <image> refresh: @image-url("icons/tabler/refresh.svg");
    out property <image> close: @image-url("icons/tabler/x.svg");
    out property <image> check: @image-url("icons/tabler/check.svg");
    out property <image> arrow-left: @image-url("icons/tabler/arrow-left.svg");
    out property <image> arrow-right: @image-url("icons/tabler/arrow-right.svg");
    out property <image> player-prev: @image-url("icons/tabler/player-track-prev.svg");
    out property <image> player-play: @image-url("icons/tabler/player-play.svg");
    out property <image> player-pause: @image-url("icons/tabler/player-pause.svg");
    out property <image> player-stop: @image-url("icons/tabler/player-stop.svg");
    out property <image> player-next: @image-url("icons/tabler/player-track-next.svg");
    out property <image> shuffle: @image-url("icons/tabler/arrows-shuffle.svg");
    out property <image> repeat: @image-url("icons/tabler/repeat.svg");
    out property <image> layout: @image-url("icons/tabler/layout-dashboard.svg");
    out property <image> settings: @image-url("icons/tabler/settings.svg");
    out property <image> cast: @image-url("icons/tabler/cast.svg");
    out property <image> volume: @image-url("icons/tabler/volume.svg");
    out property <image> music: @image-url("icons/tabler/music.svg");
    out property <image> user: @image-url("icons/tabler/user.svg");
    out property <image> disc: @image-url("icons/tabler/disc.svg");
    out property <image> category: @image-url("icons/tabler/category-2.svg");
    out property <image> calendar-time: @image-url("icons/tabler/calendar-time.svg");
    out property <image> folder: @image-url("icons/tabler/folder.svg");
}
