import { Palette } from "std-widgets.slint";

export component StatusBar inherits Rectangle {
    in property <string> status-text: "";
    in property <string> technical-info: "";
    in property <string> selection-summary: "";
    private property <string> left-status-text: root.status-text == ""
        ? root.selection-summary
        : (
            root.selection-summary == ""
                ? "Now Playing: " + root.status-text
                : "Now Playing: " + root.status-text + " | " + root.selection-summary
        );
    private property <bool> dark: Palette.color-scheme == ColorScheme.dark;

    background: root.dark ? #1a1a1a : #e9eef5;

    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 8px;

        Text {
            text: root.left-status-text;
            color: root.dark ? #aaa : #516170;
            font-size: 12px;
            vertical-alignment: center;
            overflow: elide;
            horizontal-stretch: 1;
        }

        Text {
            text: root.technical-info;
            color: root.dark ? #777 : #6a7784;
            font-size: 11px;
            vertical-alignment: center;
            overflow: elide;
            horizontal-alignment: right;
        }
    }
}
